[package]
name = "plotly"
version = "0.6.0"
description = "A plotting library powered by Plotly.js"
authors = ["Ioannis Giagkiozis <i.giagkiozis@gmail.com>"]
license = "MIT"
workspace = ".."
readme = "README.md"
homepage = "https://github.com/igiagkiozis/plotly"
documentation = "https://docs.rs/plotly"
repository = "https://github.com/igiagkiozis/plotly"
edition = "2018"
keywords = ["plot", "chart", "plotly"]

exclude = [
    "target/*"
]

[features]
# Adds plot save functionality to the following formats: png, jpeg, webp, svg, pdf and eps.
system = []
kaleido = ["plotly_kaleido"]
plotly_ndarray = ["ndarray"]

[dependencies]
plotly_kaleido = { version = "0.2.0", path = "../plotly_kaleido", optional = true }
ndarray = { version = ">=0.13.1", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
askama = "0.9.0"
rand = "0.7.3"
rand_distr = "0.2.2"


[dev-dependencies]
plotly_kaleido = { version = "0.2.0", path = "../plotly_kaleido" }
itertools = "0.9.0"
itertools-num = "0.1.3"
csv = "1.1.3"
ndarray = "0.13.1"
